#### load the dataset


In [3]:
### path = data/dataset
from PIL import Image
import os

In [2]:
# from datasets import load_dataset

# ds = load_dataset("sivan22/hebrew-handwritten-characters")

ModuleNotFoundError: No module named 'datasets'

In [ ]:
# this cell is for testing

#open an image file from the dataset
img = Image.open("../data/dataset/TRAIN/0/0_1.png")

#display the image
# img.show()

#show image pixels
print(img.size)

#resize image to 40 by 40 pixels
img = img.resize((40, 40))
print(img.size)
img.show()


#convert image to rgba and print each pixel
img = img.convert('RGBA')

#get the pixel values of the image
pixels = list(img.getdata())
binary_array = []
for pixel in pixels:
    if pixel[0] ==  255 and pixel[1] == 255 and pixel[2] == 225:
        binary_array.append(0)
    else:
        binary_array.append(1)

#print all the non 0 pixels
print(binary_array)

#convert the binary array to an image
img = Image.new('1', (40, 40))
img.putdata(binary_array)
img.show()




(120, 125)
(40, 40)
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [ ]:
# this cell is for testing

#open an image file from the dataset
img = Image.open("../data/dataset/TRAIN/0/0_1.png")

#display the image
# img.show()

#show image pixels
print(img.size)
img.show()
#resize image to 40 by 40 pixels
img = img.resize((40, 40))
print(img.size)
img.show()


#convert image to rgba and print each pixel
img = img.convert('RGBA')

#get the pixel values of the image
pixels = list(img.getdata())
binary_array = []
for pixel in pixels:
    if pixel[0] >= 128 and pixel[1] >= 128 and pixel[2] >= 128:
        binary_array.append(1)
    else:
        binary_array.append(0)

#print all the non 0 pixels
print(binary_array)

#convert the binary array to an image
img = Image.new('1', (40, 40))
img.putdata(binary_array)
img.show()




(120, 125)
(40, 40)
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

### method to convert img to arr

In [31]:
import numpy as np
import cv2

def convert_img_to_binary_array(img):
    #convert image to rgba
    img = img.resize((40, 40))  
    img = img.convert('RGBA')

    #get the pixel values of the image
    pixels = list(img.getdata())
    binary_array = []
    for pixel in pixels:
        if pixel[0] >= 128 and pixel[1] >= 128 and pixel[2] >= 128:
            binary_array.append(1)
        else:
            binary_array.append(0)
    return binary_array

def add_image_to_X_train(image, X_train):
    # Resize the image to 40x40 if it's not already
    if image.shape[:2] != (40, 40):
        image = cv2.resize(image, (40, 40), interpolation=cv2.INTER_AREA)
    
    # Convert to grayscale if the image has more than one channel
    if len(image.shape) > 2:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Convert to black and white (0 or 255)
    _, bw_image = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)
    
    # Normalize to 0 or 1 for the neural network
    normalized_image = (bw_image / 255).astype(np.float32)
    
    # Reshape to add channel dimension
    reshaped_image = normalized_image.reshape(1, 40, 40, 1)

    # Add to X_train
    if X_train is None:
        X_train = reshaped_image
    else:
        X_train = np.vstack((X_train, reshaped_image))
    return X_train

### create training and testing arrays

In [101]:
X_train = None
y_train = []

path = "../data/dataset/TRAIN/"
for folder in os.listdir(path):
    folder_path = os.path.join(path, folder)
    if not os.path.isdir(folder_path):
        continue
    if folder == "27":
        continue
    print(f"Processing folder: {folder}")
    for file in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file)
        if os.path.isfile(file_path):
            try:
                img = Image.open(file_path)

                X_train = add_image_to_X_train(np.array(img), X_train)

                y_train.append(int(folder))
            except Exception as e:
                print(f"Error processing file {file_path}: {e}")

print(X_train)
print(len(y_train))

Processing folder: 0
Processing folder: 1
Processing folder: 10
Processing folder: 11
Processing folder: 12
Processing folder: 13
Processing folder: 14
Processing folder: 15
Processing folder: 16
Processing folder: 17
Processing folder: 18
Processing folder: 19
Processing folder: 2
Processing folder: 20
Processing folder: 21
Processing folder: 22
Processing folder: 23
Processing folder: 24
Processing folder: 25
Processing folder: 26
Processing folder: 3
Processing folder: 4
Processing folder: 5
Processing folder: 6
Processing folder: 7
Processing folder: 8
Processing folder: 9
[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]


In [102]:
X_test = None
y_test = []
path = "../data/dataset/TEST/"
for folder in os.listdir(path):
    folder_path = os.path.join(path, folder)
    if not os.path.isdir(folder_path):
        continue
    if folder == "27":
        continue
    print(f"Processing folder: {folder}")
    for file in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file)
        if os.path.isfile(file_path):
            try:
                img = Image.open(file_path)
                # binary_array = convert_img_to_binary_array(img)
                X_test = add_image_to_X_train(np.array(img), X_test)

                y_test.append(int(folder))
            except Exception as e:
                print(f"Error processing file {file_path}: {e}")

Processing folder: 0
Processing folder: 1
Processing folder: 10
Processing folder: 11
Processing folder: 12
Processing folder: 13
Processing folder: 14
Processing folder: 15
Processing folder: 16
Processing folder: 17
Processing folder: 18
Processing folder: 19
Processing folder: 2
Processing folder: 20
Processing folder: 21
Processing folder: 22
Processing folder: 23
Processing folder: 24
Processing folder: 25
Processing folder: 26
Processing folder: 3
Processing folder: 4
Processing folder: 5
Processing folder: 6
Processing folder: 7
Processing folder: 8
Processing folder: 9


In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [0.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [0.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.

## split data randomly

In [103]:
X = np.concatenate((X_train, X_test))
y = np.array(np.concatenate((y_train, y_test)))

print(X.shape[0])
print(len(y))


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train size: {len(X_train)}")
print(f"Test size: {len(X_test)}")

print(f"Train size: {X_train.shape}")
print(f"Test size: {len(y_train)}")

5073
5073
Train size: 4058
Test size: 1015
Train size: (4058, 40, 40, 1)
Test size: 4058


## Create a SVM classifier

In [27]:
# svm_model = svm.SVC(probability=True)
# svm_model.fit(X_train, y_train)

model = svm.LinearSVC()
svm_model = CalibratedClassifierCV(model, cv=5, method='sigmoid')
svm_model.fit(X_train, y_train)

CalibratedClassifierCV(cv=5, estimator=LinearSVC())

In [29]:
svm_predictions = svm_model.predict_proba(X_test)
print(svm_predictions)

[[3.97770666e-02 7.34095844e-03 4.81115450e-02 ... 3.95113905e-02
  6.57683618e-02 6.39607554e-03]
 [2.40006428e-03 1.20886756e-03 1.79228058e-01 ... 1.61636914e-05
  5.04279378e-01 5.75120071e-04]
 [6.02299080e-01 1.01560495e-02 8.95812152e-02 ... 3.82510978e-04
  1.41980279e-02 4.85394154e-05]
 ...
 [2.22150093e-03 4.26245413e-02 3.87749182e-03 ... 7.36488565e-03
  1.98935295e-02 3.58497571e-02]
 [1.29328608e-02 2.63229320e-03 1.79205872e-04 ... 2.15488258e-02
  4.32957196e-02 5.15534612e-05]
 [6.03496185e-02 1.07232219e-01 6.53145189e-04 ... 2.08449213e-03
  8.12840379e-02 2.71399430e-05]]


In [30]:
# for each prediction create a dictionary with the probabilities and their label for each probability
svm_predictions_dict = []
for i in range(len(svm_predictions)):
    prediction = svm_predictions[i]
    prediction_dict = {}
    for j in range(len(prediction)):
        prediction_dict[j] = prediction[j]
    svm_predictions_dict.append(prediction_dict)

# create a dataframe from the predictions
svm_predictions_df = pd.DataFrame(svm_predictions_dict)

# add the actual labels to the dataframe
svm_predictions_df['actual'] = y_test

# add the predicted labels to the dataframe
svm_predictions_df['predicted'] = svm_model.predict(X_test)

# add the probabilities of the predicted label to the dataframe
svm_predictions_df['probability'] = svm_predictions_df.apply(lambda x: x[x['predicted']], axis=1)

# add the probabilities of the actual label to the dataframe
svm_predictions_df['actual_probability'] = svm_predictions_df.apply(lambda x: x[x['actual']], axis=1)

# add a column to the dataframe to indicate if the prediction was correct
svm_predictions_df['correct'] = svm_predictions_df['actual'] == svm_predictions_df['predicted']

# show top 10
print(svm_predictions_df.head(10))

          0         1         2         3         4         5         6  \
0  0.039777  0.007341  0.048112  0.093581  0.063427  0.011737  0.163935   
1  0.002400  0.001209  0.179228  0.001184  0.003049  0.001747  0.000040   
2  0.602299  0.010156  0.089581  0.000566  0.001722  0.000222  0.011274   
3  0.001098  0.003987  0.010627  0.027967  0.003310  0.489614  0.093625   
4  0.002363  0.006455  0.000064  0.004813  0.016255  0.002748  0.017534   
5  0.000500  0.027042  0.000103  0.007084  0.063479  0.004867  0.001498   
6  0.091787  0.042823  0.001176  0.015748  0.001863  0.005271  0.087392   
7  0.001526  0.012067  0.000940  0.029080  0.013930  0.002361  0.000247   
8  0.013121  0.006001  0.084214  0.005309  0.000670  0.099493  0.147741   
9  0.019746  0.078100  0.006859  0.018401  0.092619  0.002187  0.021563   

          7         8         9  ...        22        23        24        25  \
0  0.012981  0.003480  0.092406  ...  0.010403  0.008713  0.039511  0.065768   
1  0.000399  0

In [31]:
# calculate accuracy
svm_accuracy = accuracy_score(y_test, svm_predictions_df['predicted'])

print(f"SVM Accuracy: {svm_accuracy}")

SVM Accuracy: 0.5684729064039409


In [32]:
# save the model
import pickle
with open('../models/svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)

In [10]:
mlp = MLPClassifier(hidden_layer_sizes=(1600,100,27), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

mlp_predictions = mlp.predict_proba(X_test)

# convert to DataFrame and show the y_test and if correct
mlp_predictions_dict = []
for i in range(len(mlp_predictions)):
    prediction = mlp_predictions[i]
    prediction_dict = {}
    for j in range(len(prediction)):
        prediction_dict[j] = prediction[j]
    mlp_predictions_dict.append(prediction_dict)

mlp_predictions_df = pd.DataFrame(mlp_predictions_dict)
mlp_predictions_df['actual'] = y_test
mlp_predictions_df['predicted'] = mlp.predict(X_test)
mlp_predictions_df['probability'] = mlp_predictions_df.apply(lambda x: x[x['predicted']], axis=1)
mlp_predictions_df['actual_probability'] = mlp_predictions_df.apply(lambda x: x[x['actual']], axis=1)
mlp_predictions_df['correct'] = mlp_predictions_df['actual'] == mlp_predictions_df['predicted']

print(mlp_predictions_df.head(10))

         0         1         2        3         4         5         6  \
0  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
1  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
2  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
3  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
4  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
5  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
6  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
7  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
8  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   
9  0.03558  0.036202  0.037716  0.03925  0.038127  0.038333  0.038796   

          7         8         9  ...        22        23        24        25  \
0  0.038336  0.038464  0.037236  ...  0.032385  0.040699  0.041388  0.038575   
1  0.038336  0.038464  0.037236  ...

In [13]:
import pickle

# print accuracy
mlp_accuracy = accuracy_score(y_test, mlp_predictions_df['predicted'])
print(f"MLP Accuracy: {mlp_accuracy}")

# save the model
with open('../models/mlp_model.pkl', 'wb') as f:
    pickle.dump(mlp, f)

MLP Accuracy: 0.04827586206896552


In [104]:
from tensorflow.python.client import device_lib

def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]

print(get_available_devices())

['/device:CPU:0']


In [129]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(40, 40, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    Flatten(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(27, activation='softmax')  # 27 for 22 regular + 5 final forms
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

f:\CodeProjects\College\HebrewHandwrittenRecognition\server\.venv\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [130]:
# convert to one-hot encoding
from tensorflow.keras.utils import to_categorical

y_train_one_hot = to_categorical(y_train, 27)

history = model.fit(X_train, y_train_one_hot, 
                    epochs=20, 
                    batch_size=32)

Epoch 1/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.0916 - loss: 3.1665
Epoch 2/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.3797 - loss: 2.1285
Epoch 3/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.5092 - loss: 1.6911
Epoch 4/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.5794 - loss: 1.4699
Epoch 5/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6134 - loss: 1.3080
Epoch 6/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6394 - loss: 1.2419
Epoch 7/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6727 - loss: 1.1287
Epoch 8/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6698 - loss: 1.0829
Epoch 9/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.7094 - loss: 0.9592
Epoch 10/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7127 - loss: 0.9387
Epoch 11/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.7238 - loss: 0.9142
Epoch 12/20
127/127 ━━━━━━━━━━━━━━━━━━━━ 

In [134]:
y_test_one_hot = to_categorical(y_test, 27)

test_loss, test_acc = model.evaluate(X_test, y_test_one_hot)
print(f'Test accuracy: {test_acc}')

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7328 - loss: 1.0781
Test accuracy: 0.7408866882324219
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
[[9.1413374e-04 6.0157970e-02 5.8562635e-03 ... 8.8975072e-02
  1.1227743e-03 1.3205069e-02]
 [3.6458073e-07 1.0595186e-06 2.8323653e-04 ... 1.5589601e-05
  9.9834895e-01 2.1772391e-09]
 [9.9977368e-01 1.1336986e-07 2.0828558e-05 ... 1.0317870e-12
  1.5381431e-04 3.4558692e-13]
 ...
 [1.9606713e-08 5.6821361e-02 1.0141560e-04 ... 8.0684067e-08
  1.3945423e-07 1.2071744e-08]
 [8.2530642e-06 4.1445528e-05 3.8757164e-05 ... 2.7590760e-04
  7.7750128e-06 9.3320227e-04]
 [2.8146603e-08 9.3531591e-04 6.2006889e-06 ... 1.5804303e-04
  2.8326540e-04 7.9335329e-08]]


In [139]:
# save the model
model.save('../models/keras_model.keras')

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=../models/keras_model.

In [138]:
# prediction
predictions = model.predict(X_test)
first_prediction = predictions[0]
actual = y_test[0]

print(f"First prediction: {first_prediction}")
print(f"Actual: {actual}")

# convert to DataFrame and show the y_test and if correct
predictions_dict = []
for i in range(len(predictions)):
    prediction = predictions[i]
    prediction_dict = {}
    for j in range(len(prediction)):
        prediction_dict[j] = prediction[j]
    predictions_dict.append(prediction_dict)

predictions_df = pd.DataFrame(predictions_dict)
predictions_df['actual'] = y_test
predictions_df['predicted'] = predictions
predictions_df['probability'] = predictions_df.apply(lambda x: x[x['predicted']], axis=1)
predictions_df['actual_probability'] = predictions_df.apply(lambda x: x[x['actual']], axis=1)
predictions_df['correct'] = predictions_df['actual'] == predictions_df['predicted']

print(predictions_df.head(10))

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
First prediction: [9.14133736e-04 6.01579696e-02 5.85626345e-03 3.66565108e-01
 2.78952848e-02 1.48215843e-02 8.04656243e-04 5.04335901e-03
 9.68025706e-05 7.42418831e-03 2.36523412e-02 7.87453428e-02
 6.05869456e-04 9.25820845e-04 2.34435569e-03 1.86857639e-03
 1.37978503e-02 7.07868661e-04 1.87373196e-03 2.56946329e-02
 5.06405942e-02 1.09680116e-01 8.79086480e-02 8.67199432e-03
 8.89750719e-02 1.12277432e-03 1.32050691e-02]
Actual: 19


ValueError: Expected a 1D array, got an array with shape (1015, 27)

## Create a KNN classifier

In [ ]:
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_predictions = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_predictions)

## Create a Decision Tree classifier

In [ ]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_predictions = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_predictions)

## Create a Random Forest classifier

In [ ]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_predictions)

## Create a Naive Bayes classifier

In [ ]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_predictions = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_predictions)

# Compare the accuracies of the models


In [16]:
print("SVM Accuracy:", svm_accuracy)
# print("KNN Accuracy:", knn_accuracy)
# print("Decision Tree Accuracy:", dt_accuracy)
# print("Random Forest Accuracy:", rf_accuracy)
# print("Naive Bayes Accuracy:", nb_accuracy)

SVM Accuracy: 0.7497536945812808


In [ ]:
svm_accuracy = accuracy_score(y_test, svm_predictions)
knn_accuracy = accuracy_score(y_test, knn_predictions)
dt_accuracy = accuracy_score(y_test, dt_predictions)
rf_accuracy = accuracy_score(y_test, rf_predictions)
nb_accuracy = accuracy_score(y_test, nb_predictions)

svm_precision = precision_score(y_test, svm_predictions, average='weighted')
knn_precision = precision_score(y_test, knn_predictions, average='weighted')
dt_precision = precision_score(y_test, dt_predictions, average='weighted')
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
nb_precision = precision_score(y_test, nb_predictions, average='weighted')

svm_recall = recall_score(y_test, svm_predictions, average='weighted')
knn_recall = recall_score(y_test, knn_predictions, average='weighted')
dt_recall = recall_score(y_test, dt_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')
nb_recall = recall_score(y_test, nb_predictions, average='weighted')

svm_f1 = f1_score(y_test, svm_predictions, average='weighted')
knn_f1 = f1_score(y_test, knn_predictions, average='weighted')
dt_f1 = f1_score(y_test, dt_predictions, average='weighted')
rf_f1 = f1_score(y_test, rf_predictions, average='weighted')
nb_f1 = f1_score(y_test, nb_predictions, average='weighted')

performance_metrics = pd.DataFrame({
    'Algorithm': ['SVM', 'KNN', 'Decision Tree', 'Random Forest', 'Naive Bayes'],
    'Accuracy': [svm_accuracy, knn_accuracy, dt_accuracy, rf_accuracy, nb_accuracy],
    'Precision': [svm_precision, knn_precision, dt_precision, rf_precision, nb_precision],
    'Recall': [svm_recall, knn_recall, dt_recall, rf_recall, nb_recall],
    'F1-Score': [svm_f1, knn_f1, dt_f1, rf_f1, nb_f1]
})

print(performance_metrics)

       Algorithm  Accuracy  Precision    Recall  F1-Score
0            SVM  0.749754   0.760278  0.749754  0.748954
1            KNN  0.566502   0.613491  0.566502  0.556145
2  Decision Tree  0.414778   0.415872  0.414778  0.411652
3  Random Forest  0.689655   0.696677  0.689655  0.684458
4    Naive Bayes  0.348768   0.388866  0.348768  0.310005


c:\Users\user\Desktop\נתניה\HebrewHandwrittenRecognition\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


## Test on a manual set

In [8]:
X_manual = []
y_manual = []

path = "../data/dataset/manualTest/"
for folder in os.listdir(path):
    folder_path = os.path.join(path, folder)
    if not os.path.isdir(folder_path):
        continue
    if folder == "27":
        continue
    print(f"Processing folder: {folder}")
    for file in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file)
        if os.path.isfile(file_path):
            try:
                img = Image.open(file_path)
                binary_array = convert_img_to_binary_array(img)
                X_manual.append(binary_array)
                y_manual.append(int(folder))
            except Exception as e:
                print(f"Error processing file {file_path}: {e}")

Processing folder: 0
Processing folder: 1
Processing folder: 2
Processing folder: 3
Processing folder: 4


In [22]:
#show manuak test accuracy
import pickle
with open('./svm_model.sav', 'rb') as file:
    svm_model = pickle.load(file)
manual_predictions = svm_model.predict(X_manual)
manual_accuracy = accuracy_score(y_manual, manual_predictions)
print("Manual Test Accuracy:", manual_accuracy)
print("Manual Test Predictions:", manual_predictions)
print("Manual Test Actual:", y_manual)

#predict the 4th image
img = Image.open("../data/dataset/manualTest/1/1_01.png")
img.show()
binary_array = convert_img_to_binary_array(img)
prediction = svm_model.predict([binary_array])[0]
print("Prediction:", prediction)

NameError: name 'X_manual' is not defined